apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"operator.kubefed.io/v1alpha1","kind":"Install","metadata":{"name":"example-install"},"spec":{"size":3}}]'
    capabilities: Basic Install
    categories: "OpenShift Optional, Integration & Delivery"
    description: Gain Hybrid Cloud capabilities between your clusters with Kubernetes Federation.
    certified: "false"
    containerImage: "quay.io/pmorie/kubefed-operator:v0.0.10"
    createdAt: "2019-01-01T00:00:00Z"
    repository: https://github.com/pmorie/kubefed-operator
  name: kubefed-operator.v0.0.10
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Install
      name: installs.operator.kubefed.io
      version: v1alpha1
  displayName: Kubefed Operator
  description: |
    Kubernetes Federation is a tool to sync (aka "federate") a set of Kubernetes
    objects from a "source" into a set of other clusters. Common use-cases
    include federating Namespaces across all of your clusters or rolling out an
    application across several geographically distributed clusters. The
    Kubernetes Federation Operator runs all of the components under the hood to
    quickly get up and running with this powerful concept. Federation is a key
    part of any Hybrid Cloud capability.

    **Important Note**: This operator is purely for prototyping purposes and not
    supported by any upstream community at this time.


    **Important Note**: Currently, while in preview, this operator does not
    support automatic upgrades. You must remove the old version of the operator
    manually before installing a new version.


    ## Using Federation

    This deploys Federation in a namespace-scoped configuration which handles
    the resources only in the namespace where federation is deployed. For
    example, if you subscribe to this package in namespace `my-namespace`,
    federation will be deployed to manage objects _only_ in `my-namespace` in
    the host cluster and target clusters.

    After installing Federation instance, you will use the `kubefedctl` command
    line tool to do two types of configuration:
      
    - Configure federation to connect to your target clusters with `kubefedctl join`
    - Create new federation APIs for the API types you want to federate with `kubefedctl enable`


    **Important Note**: To add federation capability to your namespace, you are
    only required to install federation in the hosting cluster; there is no need
    to install federation in the target clusters (and no effect gained from
    doing so).


    **Important Note**: The instructions in this guide refer to the namespace
    where federation is installed as `<namespace>` in command examples. The
    upstream user guide uses `federation-system` as the name of this namespace.

    ### Get the kubefedctl CLI tool

    Before you use federation, you should ensure that you're using the binary
    for this version. You can get it from the releases on GitHub.

        curl -Ls https://github.com/kubernetes-sigs/federation-v2/releases/download/v0.0.9/kubefedctl.tgz | tar xz

    ### Joining Clusters

    Use the `kubefedctl join` command to connect clusters you want federation to
    spread resources to. `kubefedctl join` reads information about how to connect
    to the joining cluster and the cluster hosting federation from your
    KUBECONFIG.

        kubefedctl join cluster-name \
          --cluster-context mycluster \            # name of a KUBECONFIG context for the cluster to join
          --host-cluster-context mycluster \       # name of a KUBECONFIG context for the hosting cluster
          --add-to-registry \                      # add clusters to the cluster-registry
          --federation-namespace=<namespace> \     # namespace where federation is deployed
          --registry-namespace=<namespace> \       # namespace where federation is deployed
          --limited-scope=true \                   # ensure that created serviceaccount has permissions only scoped to the namespace
          -v 2
    
    `kubefedctl join` creates `FederatedCluster` and `Cluster` resources named
    `cluster-name` to represent the joined cluster.

    `Cluster` resources hold endpoint information about clusters federation connects to.

        kubectl get clusters -n <namespace>
        NAME           AGE
        cluster-name   7s
    
        kubectl get clusters cluster-name -o yaml
        apiVersion: clusterregistry.k8s.io/v1alpha1
        kind: Cluster
        metadata:
          creationTimestamp: 2019-03-12T22:51:47Z
          generation: 1
          name: cluster-name
          namespace: <namespace>
          resourceVersion: "42099"
          selfLink: /apis/clusterregistry.k8s.io/v1alpha1/namespaces/<namespace>/clusters/cluster-name
          uid: 6aa9f784-4519-11e9-baaf-02de7fb9d5b2
        spec:
          authInfo: {}
          kubernetesApiEndpoints:
            serverEndpoints:
            - clientCIDR: 0.0.0.0/0
              serverAddress: https://cluster-name.example.com:6443
        status: {}

    `FederatedCluster` resources pair `Cluster` resources to secrets holding
    `KUBECONFIG` information that federation uses to connect to `Clusters`.

        kubectl get federatedclusters -n <namespace>
        NAME           AGE
        cluster-name   7s
        
        kubectl get federatedclusters cluster-name -o yaml                                                                                                                                                                     
        apiVersion: core.federation.k8s.io/v1alpha1
        kind: FederatedCluster
        metadata:
          creationTimestamp: 2019-03-12T22:51:48Z
          generation: 1
          name: cluster-name
          namespace: <namespace>
          resourceVersion: "145794"
          selfLink: /apis/core.federation.k8s.io/v1alpha1/namespaces/<namespace>/federatedclusters/cluster-name                                                                                                         
          uid: 6ad4738c-4519-11e9-baaf-02de7fb9d5b2
        spec:
          clusterRef:
            name: cluster-name
          secretRef:
            name: cluster-name-nfs7m
        status:
          conditions:
          - lastProbeTime: 2019-03-13T01:38:02Z
            lastTransitionTime: 2019-03-12T22:57:52Z
            message: /healthz responded with ok
            reason: ClusterReady
            status: "True"
            type: Ready
          region: us-east-1
          zone: us-east-1a

    See also the upstream [user guide](https://github.com/kubernetes-sigs/federation-v2/blob/v0.0.9/docs/userguide.md#join-clusters) for more information.

    ### Unjoining Clusters

    Use the `kubefedctl unjoin` command to remove a previously joined cluster.

        kubefedctl unjoin mycluster \
          --host-cluster-context mycluster \       # name of a KUBECONFIG context for the hosting cluster
          --registry-namespace=<namespace> \       # namespace where federation is deployed
          -v 2

    This command deletes the `FederatedCluster` and `Cluster` for the unjoining
    cluster.

        kubectl get federatedclusters -n <namespace>
        No resources found.
    
        kubectl get clusters -n <namespace>
        No resources found.
    
    ### Enabling federation for new API types

    Federation allows you to spread any API type to target clusters. Use
    `kubefedctl enable <API type>` for the API types you want to add federation
    capability for. Enabling federation for an API type does two things:

    1. Creates a new API type to represent the federation API surface for that type


    2. Creates a `FederatedTypeConfig` resource that tells the federation
      controller to handle the new federation API


        kubefedctl enable deployments.extensions \
          --federation-namespace=<namespace>
    
    Running this command produces a new CRD in the hosting cluster to be the
    federation API surface for the deployments resource.

        kubectl get crd/federateddeployments.types.federation.k8s.io
        No resources found.

    `FederatedTypeConfig` resources configure federation to watch the new
    federation API surface created by `kubefedctl enable`.

        kubectl get federatedtypeconfigs -n <namespace>


    **Important Note**: Federation of a CRD requires that the CRD be installed
    on all member clusters. If the CRD is not installed on a member cluster,
    propagation to that cluster will fail.


    **Important Note**: You must enable Federation support for Namespaces in
    this configuration before other types will work. Use `kubefedctl enable
    namespaces`.


    **Important Note**: Federation is currently installed **without** any
    `FederatedTypeConfig` resources created. You must run `kubefedctl enable`
    operation for each API type you want to add federation capability for.

    See also the upstream [user guide](https://github.com/kubernetes-sigs/federation-v2/blob/v0.0.9/docs/userguide.md#enabling-federation-of-an-api-type) for more information.

    ### Example: federating deployments

    Let's do an example using the `deployments` resource.

        kubectl create -f - <<END
        apiVersion: types.federation.k8s.io/v1alpha1
        kind: FederatedDeployment
        metadata:
          name: hello
          namespace: <namespace>
        spec:
          placement:
            clusterNames:
            - cluster-name
          template:
            apiVersion: extensions/v1beta1
            kind: Deployment
            metadata:
              name: hello
            spec:
              replicas: 1
              template:
                metadata:
                  labels:
                    app: hello
                spec:
                  containers:
                  - name: hello
                    image: openshift/hello-openshift:latest
                    ports:
                    - containerPort: 80
        END

    You should be able to see the deployment in the target cluster!

        kubectl get deployments
        NAME    READY   UP-TO-DATE   AVAILABLE   AGE
        hello   1/1     1            1           33s

    ### Disabling federation for an API type

    Use the `kubefedctl disable` command to disable federation for an API type.

        kubefedctl disable deployments.extensions --federation-namespace=<namespace>

    This will disable the propagation of federated deployments, but leave the
    API surface and `FederatedTypeConfig` intact.

    To fully remove the API surface, use the `--delete-from-api` flag:

        kubefedctl disable deployments.extensions --federation-namespace=<namespace> --delete-from-api

    See also the upstream [user guide](https://github.com/kubernetes-sigs/federation-v2/blob/v0.0.9/docs/userguide.md#disabling-federation-of-an-api-type) for more information.
  keywords: ['kubernetes', 'federation', 'hybrid', 'hybrid cloud', 'multi-cluster', 'cluster']
  install:
    spec:
      deployments:
      - name: kubefed-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: kubefed-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: kubefed-operator
            spec:
              containers:
              - command:
                - kubefed-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: kubefed-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: kubefed-operator
                resources: {}
              serviceAccountName: kubefed-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - kubefed-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - operator.kubefed.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: kubefed-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.10
