apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefed-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubefed-operator
  template:
    metadata:
      labels:
        name: kubefed-operator
    spec:
      serviceAccountName: kubefed-operator
      containers:
        - name: kubefed-operator
          # Replace this with the built image name
          image: quay.io/pmorie/kubefed-operator:v0.0.10
          command:
          - kubefed-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubefed-operator"
